version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    container_name: fdp-zookeeper
  kafka:
    image: wurstmeister/kafka:2.12-2.3.1
    hostname: kafka
    container_name: fdp-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1" # 1 partition and 1 replica
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    build: ./mongo
    hostname: mongo
    container_name: fdp-mongo
  flask:
    build: ./flask
    hostname: flask
    container_name: fdp-flask
    depends_on:
      - kafka
      - mongo
    ports:
      - "5000:5000"
  spark-master:
    image: bitnami/spark:2.4.4
    hostname: spark-master
    container_name: fdp-spark-master
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"
    volumes:
      - "models:/models"
  spark-worker:
    image: bitnami/spark:2.4.4
    container_name: fdp-spark-worker
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - "models:/models"
  spark-submit:
    build: ./spark-submit
    container_name: fdp-spark-submit
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
    depends_on:
      - kafka
      - mongo
      - spark-master
      - spark-worker
    volumes:
      - "models:/models"
volumes:
  models: