version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:3.6.2
    hostname: zookeeper
    container_name: fdp-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:2.3.1
    hostname: kafka
    container_name: fdp-kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
  cassandra:
    build: ./cassandra
    hostname: cassandra
    container_name: fdp-cassandra
  flask:
    build: ./flask
    hostname: flask
    container_name: fdp-flask
    depends_on:
      - kafka
      - cassandra
    ports:
      - "5000:5000"
  spark-master:
    build: ./spark-base
    image: fdp-spark-base
    hostname: spark-master
    container_name: fdp-spark-master
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"
  spark-worker:
    image: fdp-spark-base
    container_name: fdp-spark-worker
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    depends_on:
      - spark-master
  spark-submit:
    build: ./spark-submit
    container_name: fdp-spark-submit
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
    depends_on:
      - kafka
      - cassandra
      - spark-master
      - spark-worker