version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:3.6.2
    hostname: zookeeper
    container_name: fdp-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:2.3.1
    hostname: kafka
    container_name: fdp-kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
  mongo:
    build: ./mongo
    hostname: mongo
    container_name: fdp-mongo
  flask:
    build: ./flask
    hostname: flask
    container_name: fdp-flask
    depends_on:
      - kafka
      - mongo
    ports:
      - "5000:5000"
  spark-master:
    image: bitnami/spark:2.4.4
    hostname: spark-master
    container_name: fdp-spark-master
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"
    volumes:
      - "models:/models"
  spark-worker:
    image: bitnami/spark:2.4.4
    container_name: fdp-spark-worker
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - "models:/models"
  spark-submit:
    build: ./spark-submit
    container_name: fdp-spark-submit
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
    depends_on:
      - kafka
      - mongo
      - spark-master
      - spark-worker
    volumes:
      - "models:/models"
volumes:
  models: